version: '3.8'
services:
  db:
    image: registry.redhat.io/rhel8/postgresql-96
    environment:
      - POSTGRESQL_USER=simpleblog
      - POSTGRESQL_PASSWORD=simpleblog
      - POSTGRESQL_DATABASE=simpleblog
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      - DJANGO_DB_BACKEND=psql
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=simpleblog
      - POSTGRESQL_PASSWORD=simpleblog
      - POSTGRESQL_DATABASE=simpleblog
    ports:
      - "8080:8080"
volumes:
  dbdata:
    name: dbdata
